### ISSUE TITLE
Figure out client version to freeze

### ISSUE THREAD

**Issue by VariantXYZ** [PolarisTeam/PolarisCore#3]
We need to decide on a client version. Let's assume we won't see a crazy login packet change on the next patch, so we could wait for the next maintenance and freeze there?

**Comment by Kyle873** [comment]
Seems good to me. Would it be safe to assume that if the login packet does change on a new client, it might be a good incentive to move to that version from the freeze, as it may be an indication that other packets have changed as well and that dumping from the current version wouldn't be beneficial to the current frozen version?

**Comment by VariantXYZ** [comment]
Most packets shouldn't change, the login packets end up really determining our starting point.

If we think about it, we've got a few things to worry about:
-Packets with character info
-Packets with login info
-New packets

New packets are really the least of our concerns. However, if we get login/character packets done as a priority, we should be fine freezing in a particular place. Most other packets tend to not change that often (though they might carry new data/IDs, etc...).

**Comment by Kyle873** [comment]
Basically, My biggest concern is a situation like this:

- Gather packet data for something, say acquiring an item
- The packet has changed since our frozen version and the current version that gathering is occurring on
- We assume that the data from the packet is correct, even though they actually just added a new property into the packet or rearranged the position of two properties

Thus we've gotten ourselves into a weird consistency problem where we implement the packet according to what was dumped, not to what was frozen.

I think I'm doing a shit job at explaining this, but I think you get the general idea.

I mean, in reality this shouldn't be too big of an issue, as the basic stuff we'd initially be implementing like that shouldn't be changing to begin with. However, items are an interesting case, as they contain a structure which can and will change as more properties are added to it as opposed to something like the object header which in theory should never need to change.

**Comment by VariantXYZ** [comment]
Yeah, it's a matter of what packets change relatively often, and if we can catch them in time so we can version freeze without concern...

I don't have a problem with switching, but it means for those critical packets we'd need to update them every update.

**Comment by Kyle873** [comment]
Basically, I think if while we're documenting packets and such we just make a note of "critical" packets which we need to absolutely make sure are checked between version (like login stuff, for example), then it should be fine.

**Comment by Kyle873** [comment]
Seems good. We should be okay to version freeze on the next maintenance, assuming there's a client update. That way we're absolutely sure of the version we're working with and we can make it clear. Also so that we can make a full copy and backup and put it up somewhere, since we'll probably want to have an available frozen copy for people to get ahold of and work/test with.

**Comment by VariantXYZ** [comment]
Freezing at 4.0402.1

**Comment by Kyle873** [comment]
Now we need somebody to upload a clean copy of the current client. Also providing a stripped client in the download as well.

**Comment by Sora3100** [comment]
I can try to upload one.

**Comment by Kyle873** [comment]
@Sora3100 when that's done, just drop a link on here and I'll include it in the README update. At that point the issue might as well be considered closed and further investigation in how to deal with client syncing/downgrading can continue in #34.

**Comment by Sora3100** [comment]
@Kyle873 Ah, okay, it should be done uploading by the time I get home.
